// Code generaTed by fileb0x at "2022-08-24 20:50:50.965212 +0800 CST m=+0.123469752" from config file "b0x.yaml" DO NOT EDIT.
// modified(2021-06-28 19:10:38 +0800 CST)
// original path: swagger-bootstrap/bootstrap/fonts/glyphicons-halflings-regular.woff

package file

import (
	"os"
)

// FileBootstrapFontsGlyphiconsHalflingsRegularWoff is "bootstrap/fonts/glyphicons-halflings-regular.woff"
var FileBootstrapFontsGlyphiconsHalflingsRegularWoff = []byte("")

func init() {

	f, err := FS.OpenFile(CTX, "bootstrap/fonts/glyphicons-halflings-regular.woff", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileBootstrapFontsGlyphiconsHalflingsRegularWoff)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
